version: "3.5"

services:
  bot:
    container_name: "rumbi"
    image: "rumbi_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - "postgres"
    env_file:
      - ${ENV_PATH}
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USERID=${DB_USERID}
      - DB_NAME=${DB_NAME}
    networks:
      - botnetwork
    restart: unless-stopped

  postgres:
    container_name: rumbi-db
    image: postgres
    env_file:
      - ${ENV_PATH}
    environment:
      - POSTGRES_USER=${DB_USERID}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - botnetwork
    restart: unless-stopped

  pgadmin:
    container_name: rumbi-pgadmin
    image: dpage/pgadmin4
    env_file:
      - ${ENV_PATH}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - botnetwork
    restart: unless-stopped

networks:
  botnetwork:
    driver: bridge

volumes:
  postgres:
  pgadmin:
